### ISSUE TITLE
为什么把buildToolsVersion 改为"23.0.3"，就会出现Fragment，FragmentManager，RecyclerView等等 找不到？

### ISSUE THREAD

**Issue by pjh520** [LuckyJayce/MultiTypeView#1]
compile 'com.android.support:appcompat-v7:23.4.0'
compile 'com.android.support:recyclerview-v7:23.2.1'
compile 'com.android.support:cardview-v7:23.4.0'
provided 'com.android.support:support-v4:23.4.0'
这些已加

**Comment by LuckyJayce** [comment]
这是gradle的，应该你自己去解决。
你把 buildToolsVersion 改为"23.0.3 那么上面的类库也改成
compile 'com.android.support:appcompat-v7:23.0.3'
compile 'com.android.support:recyclerview-v7:23.0.3'
compile 'com.android.support:cardview-v7:23.0.3'
